### ISSUE TITLE
AssertionErrors test_pred.py <Muskan branch>

### ISSUE THREAD

**Issue by ucalyptus** [ucalyptus/DesignLabProject#6]
**Traceback**
======================================================================
FAIL: test_expectedOutput (test_pred.TestPrediction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ucalyptus/DesignLabProject/tests/test_pred.py", line 46, in test_expectedOutput
    self.assertTrue(boolean, "Wrong Prediction")
AssertionError: False is not true : Wrong Prediction

======================================================================
FAIL: test_salary (test_pred.TestPrediction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ucalyptus/DesignLabProject/tests/test_pred.py", line 51, in test_salary
    self.assertTrue(boolean, "Invalid Salary")
AssertionError: False is not true : Invalid Salary

**Steps to reproduce this issue**
- `cd tests`
- `sh runtest.sh`

**Comment by muskan0508** [comment]
FAIL: test_salary issue resolved

**Comment by muskan0508** [comment]
FAIL: test_expectedOutput (test_pred.TestPrediction) resolved 
AssertionErrors test_pred.py <Muskan branch> #6 resloved and closed
